### ISSUE TITLE
Obsolete template files in Marathon role

### ISSUE THREAD

**Issue by rzagabe** [OGNITIO/redcell#1]
It appears like there're a few obsolete files in the template directory of the Marathon role.

https://github.com/OGNITIO/redcell/tree/master/ansible/roles/marathon/templates

From what I can see, only `mesos_authentication_secret.j2` and `default_marathon_conf.j2` seems to be used.

**Comment by eddyzags** [comment]
Indeed, the files were no longer needed since we configure the Marathon framework in the default_marathon.conf.j2 file. I make sure to remove them.
https://github.com/eddyzags/ognicluster/commit/af701b7cdb941d56ee155ef0d61153fa62cc7c78
