### ISSUE TITLE
Ensure Ansible tasks itempotence

### ISSUE THREAD

**Issue by rzagabe** [OGNITIO/redcell#2]
There're still tasks with side effects inside the install playbook (e.g. https://github.com/OGNITIO/redcell/blob/8e3cee5f88f0272eb423d8b0a823f0169ab81dd1/ansible/roles/mesos-dns/tasks/install.yml#L29) 

We must imperatively check if all tasks inside the playbooks are actually idempotent as I've noticed a some tasks add lines at the beginning of files. The `insertbefore` option in the lineinfile module prevent Ansible to check if the line exists before inserting it. We need a workaround to add the line at the beginning if and only if the line doesn't exist in the first place.

**Comment by eddyzags** [comment]
The Mesos-DNS role is now idempotent since we changed the approach by copying the entire resolv.conf file.
I make sure that all the others roles are idempotent too.
